export class Furnizor {
  nume:string;
  cui:string;
  judet:string;
  localitate:string;
  strada:string;
  nr:string;
  bl:string;
  sc:string;
  ap:string;
  telefon:string;
  email:string;
  constructor(){
    this.nume='';
    this.cui='';
    this.judet='';
    this.localitate='';
    this.strada='';
    this.nr='';
    this.bl='';
    this.sc='';
    this.ap='';
    this.telefon='';
    this.email='';
  }
}
